# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexanderwittmond/code/c++/IsingModel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexanderwittmond/code/c++/IsingModel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexanderwittmond/code/c++/IsingModel/CMakeFiles /home/alexanderwittmond/code/c++/IsingModel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexanderwittmond/code/c++/IsingModel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ising

# Build rule for target.
Ising: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ising
.PHONY : Ising

# fast build rule for target.
Ising/fast:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/build
.PHONY : Ising/fast

isingWindow.o: isingWindow.cpp.o

.PHONY : isingWindow.o

# target to build an object file
isingWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/isingWindow.cpp.o
.PHONY : isingWindow.cpp.o

isingWindow.i: isingWindow.cpp.i

.PHONY : isingWindow.i

# target to preprocess a source file
isingWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/isingWindow.cpp.i
.PHONY : isingWindow.cpp.i

isingWindow.s: isingWindow.cpp.s

.PHONY : isingWindow.s

# target to generate assembly for a file
isingWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/isingWindow.cpp.s
.PHONY : isingWindow.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/main.cpp.s
.PHONY : main.cpp.s

model.o: model.cpp.o

.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i

.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s

.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/model.cpp.s
.PHONY : model.cpp.s

ticker.o: ticker.cpp.o

.PHONY : ticker.o

# target to build an object file
ticker.cpp.o:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/ticker.cpp.o
.PHONY : ticker.cpp.o

ticker.i: ticker.cpp.i

.PHONY : ticker.i

# target to preprocess a source file
ticker.cpp.i:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/ticker.cpp.i
.PHONY : ticker.cpp.i

ticker.s: ticker.cpp.s

.PHONY : ticker.s

# target to generate assembly for a file
ticker.cpp.s:
	$(MAKE) -f CMakeFiles/Ising.dir/build.make CMakeFiles/Ising.dir/ticker.cpp.s
.PHONY : ticker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Ising"
	@echo "... edit_cache"
	@echo "... isingWindow.o"
	@echo "... isingWindow.i"
	@echo "... isingWindow.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... ticker.o"
	@echo "... ticker.i"
	@echo "... ticker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

